config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'public#index'

  namespace :api do
    resource :user, only: [] do
      post '/sign_up', to: 'user/registrations#create', on: :collection
      post '/sign_in', to: 'user/sessions#create', on: :collection
      post '/account', to: 'user/account#update', on: :collection
      post '/password', to: 'user/account#update_password', on: :collection
      get '/reset_password', to: 'user/passwords#new'
      post '/reset_password', to: 'user/passwords#create'
      post '/update_password', to: 'user/passwords#update'
      get '/profile', to: 'user/profile#show'
      get '/user_by_email', to: 'user/profile#user_by_email'
    end

    resource :company, only: [] do
      get '/companies', to: 'company/company#index'
      get '/company/:id', to: 'company/company#show'
      post '/update', to: 'company/company#update'
      post '/create', to: 'company/company#create'
    end

    resource :invitation, only: [] do
      get '/invitations', to: 'invitation/invitation#index'
      get '/invitation/:id', to: 'invitation/invitation#show'
      post '/update', to: 'invitation/invitation#update'
      post '/create', to: 'invitation/invitation#create'
    end

    resource :city, only: [] do
      get '/cities', to: 'city/city#index'
      get '/city', to: 'city/city#show'
    end

    resource :country, only: [] do
      get '/countries', to: 'country/country#index'
      get '/country/:id', to: 'country/country#show'
    end

    resource :state, only: [] do
      get '/states', to: 'state/state#index'
      get '/state/:id', to: 'state/state#show'
    end

    resource :user_company_type, only: [] do
      get '/user_company_types', to: 'user_company_type/user_company_type#index'
      get '/user_company_type', to: 'user_company_type/user_company_type#show'
      get '/company_types_by_user', to: 'user_company_type/user_company_type#company_types_by_user'
    end

    resource :user_type, only: [] do
      get '/user_types', to: 'user_type/user_type#index'
      get '/user_type', to: 'user_type/user_type#show'
    end

    resource :event, only: [] do
      get '/events', to: 'event/event#index'
      get '/event/:id', to: 'event/event#show'
      post '/update', to: 'event/event#update'
      post '/create', to: 'event/event#create'
    end

    resource :invitation_type, only: [] do
      get '/invitation_types', to: 'invitation_type/invitation_types#index'
      get '/invitation_type', to: 'invitation_type/invitation_type#show'
    end

    namespace :user do
      resources :users
    end

    resource :event, only: [] do
      get '/events_by_user', to: 'event/event#events_by_user'
    end

    resource :event_type, only: [] do
      get '/event_types', to: 'event_type/event_type#index'
    end

    resource :event_category, only: [] do
      get '/event_categories', to: 'event_category/event_categories#index'
    end
  end

  # namespace :admin do
  #   root 'admins#index'
  #   resources :cities
  #   resources :companies
  #   resources :countries
  #   resources :event_categories
  #   resources :event_types
  #   resources :events
  #   resources :invitations
  #   resources :invitation_types
  #   resources :states
  #   resources :user_company_types
  #   resources :user_types
  # end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/__1admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_filter :authenticate_admin!

  layout 'admin'

  def index
  end
end

app/controllers/__1admin/cities_controller.rb
class Admin::CitiesController < Admin::AdminsController
  before_action :set_admin_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all
  end

  def new
    @city = City.new
    @city.state_id = params[:format]
  end

  def create
    @city = City.create(permitted_columns)

    if @city.errors.any?
      render :new
    else
      redirect_to admin_cities_path
    end
  end

  def edit
  end

  def update
    @city.update_attributes(permitted_columns)

    redirect_to admin_cities_path
  end

  def show
  end

  def destroy
    if @city.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_cities_path
  end

  private
    def set_admin_city
      @city = City.find(params[:id])
    end

    def permitted_columns
      params.require(:city).permit(:name, :state_id)
    end
end

app/controllers/__1admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminsController
  before_action :set_admin_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create(permitted_columns)

    if @company.errors.any?
      render :new
    else
      redirect_to admin_companies_path
    end
  end

  def edit
  end

  def update
    @company.update_attributes(permitted_columns)

    redirect_to admin_companies_path
  end

  def show
  end

  def destroy
    if @company.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_companies_path
  end

  private
    def set_admin_company
      @company = Company.find(params[:id])
    end

    def permitted_columns
      params.require(:company).permit(:title, :description, :max_users, :min_users)
    end
end

app/controllers/__1admin/countries_controller.rb
class Admin::CountriesController < Admin::AdminsController
  before_action :set_admin_country, only: [:show, :edit, :update, :destroy]

  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.create(permitted_columns)

    if @country.errors.any?
      render :new
    else
      redirect_to admin_countries_path
    end
  end

  def edit
  end

  def update
    @country.update_attributes(permitted_columns)

    redirect_to admin_countries_path
  end

  def show
  end

  def destroy
    if @country.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_countries_path
  end

  private
    def set_admin_country
      @country = Country.find(params[:id])
    end

    def permitted_columns
      params.require(:country).permit(:name, :initials)
    end
end

app/controllers/__1admin/event_categories_controller.rb
class Admin::EventCategoriesController < Admin::AdminsController
  before_action :set_admin_event_category, only: [:show, :edit, :update, :destroy]

  def index
    @event_categories = EventCategory.all
  end

  def new
    @event_category = EventCategory.new
  end

  def create
    @event_category = EventCategory.create(permitted_columns)

    if @event_category.errors.any?
      render :new
    else
      redirect_to admin_event_categories_path
    end
  end

  def edit
  end

  def update
    @event_category.update_attributes(permitted_columns)

    redirect_to admin_event_categories_path
  end

  def show
  end

  def destroy
    if @event_category.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_event_categories_path
  end

  private
    def set_admin_event_category
      @event_category = EventCategory.find(params[:id])
    end

    def permitted_columns
      params.require(:event_category).permit(:title, :short_description, :long_description)
    end
end

app/controllers/__1admin/event_types_controller.rb
class Admin::EventTypesController < Admin::AdminsController
  before_action :set_admin_event_type, only: [:show, :edit, :update, :destroy]

  def index
    @event_types = EventType.all
  end

  def new
    @event_type = EventType.new
  end

  def create
    @event_type = EventType.create(permitted_columns)

    if @event_type.errors.any?
      render :new
    else
      redirect_to admin_event_types_path
    end
  end

  def edit
  end

  def update
    @event_type.update_attributes(permitted_columns)

    redirect_to admin_event_types_path
  end

  def show
  end

  def destroy
    if @event_type.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_event_types_path
  end

  private
    def set_admin_event_type
      @event_type = EventType.find(params[:id])
    end

    def permitted_columns
      params.require(:event_type).permit(:title, :short_description, :long_description)
    end
end

app/controllers/__1admin/events_controller.rb
class Admin::EventsController < Admin::AdminsController
  before_action :set_admin_event, only: [:show, :edit, :update, :destroy]

  def index
    @admin_events = Event.all
  end

  def show
  end

  def new
    @admin_event = Event.new
  end

  def edit
  end

  def create
    @admin_event = Event.create(permitted_columns)

    if @admin_event.errors.any?
      render :new
    else
      redirect_to admin_events_path
    end
  end

  def update
    @admin_event.update_attributes(permitted_columns)

    redirect_to admin_events_path
  end

  def destroy
    if @admin_event.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_events_path
  end

  private
    def set_admin_event
      @admin_event = Event.find(params[:id])
    end

    def permitted_columns
      params.require(:event).permit(:title, :short_description, :long_description, :city_id, :address, :address_complement, :number, :district, :zip_code, :latitude, :longitude, :url_site, :facebook_page, :initial_date, :end_date, :initial_hour, :end_hour, :status, :note, :archive, :event_type_id, :event_category_id, :use_password, :password, :confirm_password, :min_users, :max_users, :company_id)
    end
end

app/controllers/__1admin/invitation_types_controller.rb
class Admin::InvitationTypesController < Admin::AdminsController
  before_action :set_admin_invitation_type, only: [:show, :edit, :update, :destroy]

  def index
    @invitation_types = InvitationType.all
  end

  def new
    @invitation_type = InvitationType.new
  end

  def create
    @invitation_type = InvitationType.create(permitted_columns)

    if @invitation_type.errors.any?
      render :new
    else
      redirect_to admin_invitation_types_path
    end
  end

  def edit
  end

  def update
    @invitation_type.update_attributes(permitted_columns)

    redirect_to admin_invitation_types_path
  end

  def show
  end

  def destroy
    if @invitation_type.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_invitation_types_path
  end

  private
    def set_admin_invitation_type
      @invitation_type = InvitationType.find(params[:id])
    end

    def permitted_columns
      params.require(:invitation_type).permit(:title, :short_description, :long_description)
    end
end

app/controllers/__1admin/invitations_controller.rb
class Admin::InvitationsController < Admin::AdminsController
  before_action :set_admin_invitation, only: [:show, :edit, :update, :destroy]

  def index
    @invitations = Invitation.all
  end

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.create(permitted_columns)

    if @invitation.errors.any?
      render :new
    else
      redirect_to admin_invitations_path
    end
  end

  def edit
  end

  def update
    @invitation.update_attributes(permitted_columns)

    redirect_to admin_invitations_path
  end

  def show
  end

  def destroy
    if @invitation.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_invitations_path
  end

  private
    def set_admin_invitation
      @invitation = Invitation.find(params[:id])
    end

    def permitted_columns
      params.require(:invitation).permit(:event_id, :guest_user_id, :invitation_type_id, :host_user_id)
    end
end

app/controllers/__1admin/states_controller.rb
class Admin::StatesController < Admin::AdminsController
  before_action :set_admin_state, only: [:show, :edit, :update, :destroy]

  def index
    @states = State.all
  end

  def new
    @state = State.new
    @state.country_id = params[:format]
  end

  def create
    @state = State.create(permitted_columns)

    if @state.errors.any?
      render :new
    else
      redirect_to admin_states_path
    end
  end

  def edit
  end

  def update
    @state.update_attributes(permitted_columns)

    redirect_to admin_states_path
  end

  def show
  end

  def destroy
    if @state.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_states_path
  end

  private
    def set_admin_state
      @state = State.find(params[:id])
    end

    def permitted_columns
      params.require(:state).permit(:name, :initials, :country_id)
    end
end

app/controllers/__1admin/user_company_types_controller.rb
class Admin::UserCompanyTypesController < Admin::AdminsController
  before_action :set_admin_user_company_type, only: [:show, :edit, :update, :destroy]

  def index
    @user_company_types = UserCompanyType.all
  end

  def new
    @user_company_type = UserCompanyType.new
  end

  def create
    @user_company_type = UserCompanyType.create(permitted_columns)

    if @user_company_type.errors.any?
      render :new
    else
      redirect_to admin_user_company_types_path
    end
  end

  def edit
  end

  def update
    @user_company_type.update_attributes(permitted_columns)

    redirect_to admin_user_company_type_path
  end

  def show
  end

  def destroy
    if @user_company_type.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_user_company_types_path
  end

  private
    def set_admin_user_company_type
      @user_company_type = UserCompanyType.find(params[:id])
    end

    def permitted_columns
      params.require(:user_company_type).permit(:user_id, :company_id, :user_type_id, :active, :admin)
    end
end

app/controllers/__1admin/user_types_controller.rb
class Admin::UserTypesController < Admin::AdminsController
  before_action :set_admin_user_type, only: [:show, :edit, :update, :destroy]

  def index
    @user_types = UserType.all
  end

  def new
    @user_type = UserType.new
  end

  def create
    @user_type = UserType.create(permitted_columns)

    if @user_type.errors.any?
      render :new
    else
      redirect_to admin_user_types_path
    end
  end

  def edit
  end

  def update
    @user_type.update_attributes(permitted_columns)

    redirect_to admin_user_types_path
  end

  def show
  end

  def destroy
    if @user_type.destroy
      flash[:notice] = 'Delete success'
    else
      flash[:notice] = 'Delete error'
    end
    redirect_to admin_user_types_path
  end

  private
    def set_admin_user_type
      @user_type = UserType.find(params[:id])
    end

    def permitted_columns
      params.require(:user_type).permit(:title, :short_description, :long_description)
    end
end

app/controllers/api/event/event_controller.rb
class Api::Event::EventController < ApplicationController

  def index
    events = Event.all
    render json: { events: events }
  end

  def show
    event = Event.find(params[:id])
    render json: { event: event }
  end

  def update
    @event = Event.find_by_id(params[:event][:id])
    event = @event.update(update_params)
    if event
      head :ok
    else
      render json: event.errors.full_messages, status: :unprocessable_entity
    end
  end

  def create
    @event = Event.new(create_params)
    if @event.save
      render json: @event, status: :created, root: :event
    else
      render json: @event.errors.full_messages
    end
  end

  private
  def create_params
    params.require(:event).permit(:title, :short_description, :long_description, :initial_date, :end_date, :initial_hour, :end_hour, :min_users, :max_users, :company_id)
  end

  def update_params
    params.require(:event).permit(:title, :short_description, :long_description, :initial_date, :end_date, :initial_hour, :end_hour, :min_users, :max_users, :company_id)
  end
end

app/helpers/api/event/event_helper.rb
module Api::Event::EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/__1admin/events/_form.haml
= simple_form_for [:admin, @admin_event] do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :short_description
    = f.input :long_description
    = f.input :zip_code
    = f.label :city_id
    = f.collection_select :city_id, City.all, :id, :name, {prompt: 'Select a City'}, {class: 'form-control'}
    %br
    = f.input :address
    = f.input :address_complement
    = f.input :number
    = f.input :district
    = f.input :latitude
    = f.input :longitude
    = f.input :url_site
    = f.input :facebook_page
    = f.input :initial_date
    = f.input :end_date
    = f.input :initial_hour
    = f.input :end_hour
    = f.input :status
    = f.input :note
    = f.input :archive
    = f.label :event_type_id
    = f.collection_select :event_type_id, EventType.all, :id, :title, {prompt: 'Select a type'}, {class: 'form-control'}
    %br
    = f.label :event_category_id
    = f.collection_select :event_category_id, EventCategory.all, :id, :title, {prompt: 'Select a type'}, {class: 'form-control'}
    = f.input :use_password
    = f.input :password
    = f.input :confirm_password
    = f.input :min_users
    = f.input :max_users
    = f.label :company_id
    = f.collection_select :company_id, Company.all, :id, :name, {prompt: 'Select a type'}, {class: 'form-control'}
    %br
  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-primary'

app/views/__1admin/events/edit.haml
%h1 Editing Admin Event

= render 'form'
%br
= link_to 'Back', admin_events_url

app/views/__1admin/events/index.haml
%p#notice= notice
%h1 Listing Admin Events
%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Short description
      %th City
      %th Initial date
      %th End date
      %th Initial hour
      %th End hour
      %th Status
      %th Archive
      %th Event type
      %th Event category
      %th Min users
      %th Max users
      %th Company
      %th
  %tbody
    - @admin_events.each do |admin_event|
      %tr
        %td= link_to admin_event.title, admin_event_url(admin_event)
        %td= admin_event.short_description
        %td= admin_event.city.name
        %td= admin_event.initial_date
        %td= admin_event.end_date
        %td= admin_event.initial_hour
        %td= admin_event.end_hour
        %td= admin_event.status
        %td= admin_event.archive
        %td= admin_event.event_type.title
        %td= admin_event.event_category.title
        %td= admin_event.min_users
        %td= admin_event.max_users
        %td= admin_event.company_id
        %td
          = link_to 'Edit', edit_admin_event_path(admin_event), class: 'btn btn-warning'
          = link_to 'Delete', admin_event_url(admin_event), method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' }
= link_to 'New Event', new_admin_event_path, class: 'btn btn-primary'

app/views/__1admin/events/new.haml
%h1 New Admin Event
= render 'form'
%br
= link_to 'Back', admin_events_url

app/views/__1admin/events/show.haml
%p#notice= notice
%p
  %strong Title:
  = @admin_event.title
%p
  %strong Short description:
  = @admin_event.short_description
%p
  %strong Long description:
  = @admin_event.long_description
%p
  %strong City:
  = @admin_event.city_id
%p
  %strong Address:
  = @admin_event.address
%p
  %strong Address complement:
  = @admin_event.address_complement
%p
  %strong Number:
  = @admin_event.number
%p
  %strong District:
  = @admin_event.district
%p
  %strong Zip code:
  = @admin_event.zip_code
%p
  %strong Latitude:
  = @admin_event.latitude
%p
  %strong Longitude:
  = @admin_event.longitude
%p
  %strong Url site:
  = @admin_event.url_site
%p
  %strong Facebook page:
  = @admin_event.facebook_page
%p
  %strong Initial date:
  = @admin_event.initial_date
%p
  %strong End date:
  = @admin_event.end_date
%p
  %strong Initial hour:
  = @admin_event.initial_hour
%p
  %strong End hour:
  = @admin_event.end_hour
%p
  %strong Status:
  = @admin_event.status
%p
  %strong Note:
  = @admin_event.note
%p
  %strong Archive:
  = @admin_event.archive
%p
  %strong Event type:
  = @admin_event.event_type_id
%p
  %strong Event category:
  = @admin_event.event_category_id
%p
  %strong Use password:
  = @admin_event.use_password
%p
  %strong Password:
  = @admin_event.password
%p
  %strong Confirm password:
  = @admin_event.confirm_password
%p
  %strong Min users:
  = @admin_event.min_users
%p
  %strong Max users:
  = @admin_event.max_users
%p
  %strong Company:
  = @admin_event.company_id

%br
= link_to 'Edit', edit_admin_event_path(@admin_event), class: 'btn btn-warning'
%br
%br
= link_to 'Back', admin_events_url